### ISSUE TITLE
Only *.scss files are published.

### ISSUE THREAD

**Issue by dailytabs** [webjars/datatables-fixedheader#5]
https://mvnrepository.com/artifact/org.webjars/datatables-fixedheader

All of the 3.1.x artifacts only include the SASS files in the css directory.

Is this normal? None of the other datatables plugins/extensions that I am using from webjars are like this. This makes it impossible to use. Its useless.

I even use SASS in my project, but it's impossible to get a reference to the SASS files into my build process, since they are stuck in jars.

What is the point of this? I am really hoping it is a bug...

Oh, and v3.1.7 is out, too.

**Comment by jamesward** [comment]
I guess the original author of this webjar didn't need the compiled files because they were probably using a compiler as part of their build pipeline.  Nonetheless, I've added those and am releasing `3.1.7` now.

**Comment by dailytabs** [comment]
Forgot to say thanks. So, thanks!
